name: Playwright Tests

on:
  schedule:
   # - cron: '30 21 * * 1-4'  # Mon-Fri 8PM IST
  # push:
  #   branches: [main]
  # pull_request:
  #   branches: [main]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment'
        required: true
        default: 'QA'
        type: choice
        options:
          - QA
          - PROD
          

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 8
    environment: ${{ github.event.inputs.environment || 'QA' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      - name: Cache Playwright browsers
        id: playwright-cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps chromium

      - name: Install Playwright OS deps only (if cached)
        if: steps.playwright-cache.outputs.cache-hit == 'true'
        run: npx playwright install-deps chromium

      - name: Run tests
        run: npx playwright test --project=chromium
        env:
          ENV: ${{ github.event.inputs.environment || 'QA' }}
          BASE_URL: ${{ secrets.BASE_URL }}
          ORG_ADMIN: ${{ secrets.ORG_ADMIN }}
          PASSWORD: ${{ secrets.PASSWORD }}
          PHYSICIAN_ROLE: ${{ secrets.PHYSICIAN_ROLE }}
          CUSTOM_ROLE: ${{ secrets.CUSTOM_ROLE }}
          TECHADMIN_ROLE: ${{ secrets.TECHADMIN_ROLE }}
          MARKETING_ROLE: ${{ secrets.MARKETING_ROLE }}
          CLINICAL_ROLE: ${{ secrets.CLINICAL_ROLE }}
          DIETICIAN_ROLE: ${{ secrets.DIETICIAN_ROLE }}
          CARECOORDINATOR_ROLE: ${{ secrets.CARECOORDINATOR_ROLE }}
          NURSE_ROLE: ${{ secrets.NURSE_ROLE }}

      - name: Upload HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report-${{ github.run_id }}
          path: reports/html-report/
          retention-days: 30

      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-${{ github.run_id }}
          path: allure-results/
          retention-days: 30